server:
  port: 8083

spring:
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://postgres:5432/library}
    username: ${SPRING_R2DBC_USERNAME:postgres}
    password: ${SPRING_R2DBC_PASSWORD:1234}
  sql:
    init:
      mode: always
jwt:
  secret: ${JWT_SECRET:B7sT5lsNO-YktTYcqUQn1NnkNerKFdlzT6qWwAcsHb0=}
