services:

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    networks:
      - lms-net

  auth-service:
    build: ./auth-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/library
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      JWT_SECRET: 'B7sT5lsNO-YktTYcqUQn1NnkNerKFdlzT6qWwAcsHb0='
    ports:
      - "8081:8081"
    networks:
      - lms-net

  user-service:
    build: ./user-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/library
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      JWT_SECRET: 'B7sT5lsNO-YktTYcqUQn1NnkNerKFdlzT6qWwAcsHb0='
    ports:
      - "8082:8082"
    networks:
      - lms-net

  book-service:
    build: ./book-service
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/library
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: 1234
      JWT_SECRET: 'B7sT5lsNO-YktTYcqUQn1NnkNerKFdlzT6qWwAcsHb0='
    ports:
      - "8083:8083"
    networks:
      - lms-net

  borrow-service:
    build: ./borrow-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/library
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      JWT_SECRET: 'B7sT5lsNO-YktTYcqUQn1NnkNerKFdlzT6qWwAcsHb0='
      BOOK_SERVICE_URL: http://book-service:8083/books
    ports:
      - "8084:8084"
    networks:
      - lms-net

  api-gateway:
    build: ./api-gateway
    environment:
      JWT_SECRET: 'B7sT5lsNO-YktTYcqUQn1NnkNerKFdlzT6qWwAcsHb0='
    ports:
      - "8080:8080"
    networks:
      - lms-net

networks:
  lms-net:
    driver: bridge
